# Generated by Django 3.1.1 on 2020-10-05 23:14

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('inv', '0001_initial'), ('inv', '0002_auto_20200906_0905'), ('inv', '0003_auto_20200906_0921'), ('inv', '0004_auto_20200906_0929'), ('inv', '0005_items_item_qty'), ('inv', '0006_auto_20200906_1229'), ('inv', '0007_auto_20200906_1237'), ('inv', '0008_auto_20200906_1738'), ('inv', '0009_auto_20200908_1028'), ('inv', '0010_auto_20200908_1033'), ('inv', '0011_auto_20200916_1818'), ('inv', '0012_auto_20200917_0914'), ('inv', '0013_auto_20200917_0915'), ('inv', '0014_auto_20200917_2126'), ('inv', '0015_auto_20200917_2222'), ('inv', '0016_auto_20200918_1930'), ('inv', '0017_auto_20200928_1448'), ('inv', '0018_keywords_keyword_slug')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('keyword', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('keyword_desc', models.CharField(blank=True, max_length=100)),
                ('keyword_slug', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Keywords',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(default='staff name', max_length=100)),
                ('staff_title', models.CharField(blank=True, max_length=50)),
                ('staff_contact', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_loc', models.CharField(blank=True, max_length=200)),
                ('warehouse_details', models.CharField(blank=True, max_length=300)),
                ('warehouse_name', models.CharField(default='warehouse', max_length=100)),
                ('warehouse_img', models.CharField(blank=True, default='warehouse.png', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Warehouses',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_desc', models.CharField(blank=True, max_length=500)),
                ('item_img', models.CharField(blank=True, max_length=50)),
                ('item_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('item_owner_staff_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='inv.staff')),
                ('item_name', models.CharField(default='name', max_length=50)),
                ('item_qty', models.IntegerField(default='1')),
                ('item_consumable', models.BooleanField(default=False)),
                ('item_remaining', models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Percent Remaining')),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Boxes',
            fields=[
                ('box_id', models.AutoField(primary_key=True, serialize=False)),
                ('box_location', models.CharField(blank=True, max_length=300)),
                ('box_description', models.CharField(blank=True, max_length=300)),
                ('other_box_details', models.CharField(blank=True, max_length=300)),
                ('warehouse', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bx_wh', to='inv.warehouse')),
                ('box_name', models.CharField(default='box', max_length=20)),
                ('box_img', models.CharField(blank=True, default='box.png', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Boxes',
            },
        ),
        migrations.CreateModel(
            name='Keywords_in_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kw_itm', to='inv.items')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kw_kw', to='inv.keywords')),
            ],
            options={
                'verbose_name_plural': 'Keywords in Items',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inv_id', models.AutoField(primary_key=True, serialize=False)),
                ('inv_date', models.DateField(default=datetime.date.today)),
                ('inv_comment', models.CharField(default='an inventory was conducted', max_length=500)),
                ('inv_box', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inv.boxes')),
                ('inv_item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inv.items')),
                ('inv_warehouse', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inv.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.CreateModel(
            name='Items_in_boxes',
            fields=[
                ('txn_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_from', models.DateField(default=django.utils.timezone.now)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(default='add to database', max_length=100)),
                ('box_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bx_id', to='inv.boxes')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itm_id', to='inv.items')),
                ('moved_by_staff_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inv.staff')),
            ],
            options={
                'verbose_name_plural': 'Items in Boxes',
            },
        ),
    ]
