# Generated by Django 3.1.1 on 2020-10-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0017_auto_20200928_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='keyword_slug',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
